# Generated by Django 6.0.7 on 2026-07-16 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección (calle y número)')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('categoria', models.CharField(choices=[('SEGURIDAD', '🚨 Seguridad'), ('INFRAESTRUC', '💡 Infraestructura'), ('MEDIOAMBIENTE', '🌳 Medio Ambiente'), ('TRANSITO', '🚗 Tránsito y Transporte'), ('CONVIVENCIA', '🏘 Convivencia Vecinal'), ('OTRO', '📋 Otro')], max_length=15, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación específica')),
                ('horario', models.JSONField(blank=True, default=list, verbose_name='Horario en que ocurre')),
                ('ocurrido_antes', models.TextField(blank=True, verbose_name='¿Ha ocurrido antes? ¿Cuándo?')),
                ('urgencia', models.CharField(choices=[('URGENTE', '🔴 Urgente — acción inmediata'), ('ALTA', '🟡 Alta — dentro de esta semana'), ('MEDIA', '🟢 Media — dentro del mes'), ('BAJA', '⚪ Baja — sin urgencia inmediata')], max_length=10, verbose_name='Urgencia')),
                ('desc_evidencia', models.TextField(blank=True, verbose_name='Descripción de evidencia disponible')),
                ('notas_adicionales', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Denuncia Vecinal',
                'verbose_name_plural': 'Denuncias Vecinales',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('canal', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('EMAIL', 'Correo electrónico')], max_length=15, verbose_name='Canal de atención')),
                ('motivo', models.CharField(choices=[('TRAMITE_PERSONAL', 'Trámite personal'), ('BENEFICIO', 'Postulación a beneficio'), ('MATRICULA', 'Matrícula escolar'), ('ACREDITACION', 'Acreditación de domicilio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Motivo')),
                ('motivo_otro', models.CharField(blank=True, max_length=200, verbose_name='Motivo (especificar)')),
                ('es_socio', models.BooleanField(verbose_name='¿Es socio/a de la JJVV?')),
                ('boleta_servicio', models.FileField(blank=True, null=True, upload_to='boletas/%Y/%m/', verbose_name='Boleta de servicio (luz o agua)')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autoriza uso de datos personales')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Solicitud de Certificado',
                'verbose_name_plural': 'Solicitudes de Certificado',
                'ordering': ['-creado_en'],
            },
        ),
    ]
