# Generated by Django 6.0.7 on 2026-08-05 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('CONVIVIENTE', 'Conviviente civil'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a')], max_length=15, verbose_name='Estado civil')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Profesión / Ocupación')),
                ('villa', models.CharField(choices=[('CONCEPCION', 'Villa Concepción'), ('EL_ROCIO', 'Villa El Rocío')], max_length=15, verbose_name='Villa')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección (calle y número)')),
                ('condicion', models.CharField(choices=[('PROPIETARIO', 'Propietario/a'), ('ARRENDATARIO', 'Arrendatario/a'), ('OTRO', 'Otra situación')], max_length=15, verbose_name='Condición de vivienda')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autoriza uso de datos personales')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Solicitud de Ingreso',
                'verbose_name_plural': 'Solicitudes de Ingreso',
                'ordering': ['-creado_en'],
            },
        ),
    ]
